name: Build iOS IPA - Vector Cleanup Fix

on:
  push:
    branches: [ fix/vector-cleanup-minimal ]
  workflow_dispatch: # Allow manual triggering

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        channel: 'stable'
        cache: true
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Verify the installation
      run: flutter doctor -v
      
    - name: Generate mocks
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      
    - name: Analyze project source
      run: flutter analyze
      
    - name: Run tests
      run: flutter test --coverage --reporter=expanded

  build-ios:
    name: Build iOS (No Signing)
    runs-on: macos-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        channel: 'stable'
        cache: true
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Build iOS (no signing)
      run: |
        flutter build ios --no-codesign --debug
        echo "✅ iOS build successful - vector cleanup implementation is compatible"
